env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
addr = ":8080"
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 10

[cookie]
# cookie: lang, ccy, by
domain = "yiwen.ltd"
secure = false
expires_in = 604800  # 60*60*24*7 seconds

[oss]
bucket = "yiwenai"
endpoint = "oss-cn-hangzhou.aliyuncs.com"
access_key_id = ""
access_key_secret = ""

[ssr]
ssr_host = "webscraper.base:8080"
robots = [
  "Googlebot",
  "Bingbot",
  "Slurp",
  "DuckDuckBot",
  "Baiduspider",
  "YandexBot",
  "Sogou",
  "Exabot",
  "facebot",
  "Applebot",
  "Spider",
  "robot",
]

[assets."/"]
"*" = "oss://dev/web/dist/index.html"
"favicon.ico" = "oss://favicon.ico"
"robots.txt" = "oss://robots.txt"
