name: Docker
on:
  push:
    tags:
      - 'v*'
env:
  IMAGE_NAME: ywserver/yiwen-static
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build the Docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
          docker login --username ${{ secrets.CR_USERNAME }} --password ${{ secrets.CR_PASSWORD }} ${{ secrets.CR_REGISTRY }}
          IMAGE_TAG="${{ secrets.CR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          TAGS="-t ${IMAGE_TAG}"
          docker buildx build --platform='linux/amd64,linux/arm64' $TAGS --push .
